import json, os, re

DATA_DIR = 'c:/Users/oussa/Desktop/pro-fix/system/data'

LANG_KEYS = {'es', 'en', 'fr', 'ar'}

# Exact phrase replacements (case-insensitive, longest first)
EXACT_REPLACEMENTS = [
    # Spanish phrases found in Arabic sections
    ('MMI Touch Response con procesador de 10 núcleos', 'نظام إم إم آي تاتش ريسبونس بمعالج 10 نوى'),
    ('Audi Connect con navegación en línea, tráfico y avisos de velocidad', 'أودي كونكت مع ملاحة عبر الإنترنت وحركة المرور وتنبيهات السرعة'),
    ('Sistema de sonido Audi 10 altavoces', 'نظام صوت أودي بـ 10 مكبرات صوت'),
    ('Bang & Olufsen 15 altavoces y 705 W', 'بانغ أند أولوفسن 15 مكبر صوت و 705 واط'),
    ('BMW Live Cockpit Professional 12.3" con gráficos M', 'لوحة بي إم دبليو المهنية 12.3 بوصة برسومات أم'),
    ('BMW Operating System 8.5 con iDrive', 'نظام بي إم دبليو 8.5 مع آي درايف'),
    ('BMW Operating System 8.5 con iDrive y control por voz', 'نظام بي إم دبليو 8.5 مع آي درايف والتحكم الصوتي'),
    ('Apple CarPlay inalámbrico', 'أبل كاربلاي لاسلكي'),
    ('Android Auto inalámbrico', 'أندرويد أوتو لاسلكي'),
    ('Carga inalámbrica', 'شحن لاسلكي'),
    ('Harman Kardon Logic 7 de 16 altavoces y 464 W', 'هارمان كاردون لوجيك 7 بـ 16 مكبر صوت و 464 واط'),
    ('Bang & Olufsen Advanced Sound System بـ 19 مكبر صوت وقوة 755 واط', 'بانغ أند أولوفسن أدفانسد ساوند سيستم 19 مكبر صوت وقوة 755 واط'),
    ('Apple CarPlay/Android Auto', 'أبل كاربلاي / أندرويد أوتو'),
    ('con navegación', 'مع الملاحة'),
    ('con desbloqueo remoto', 'مع الفتح عن بعد'),
    ('con navegación en línea', 'مع الملاحة عبر الإنترنت'),
    ('altavoces', 'مكبرات صوت'),
    ('pulgadas', 'بوصة'),
    ('pulgada', 'بوصة'),
    ('inalámbrico', 'لاسلكي'),
    ('inalámbrica', 'لاسلكي'),
    ('y control por voz', 'والتحكم الصوتي'),
    ('Cámara 360', 'كاميرا 360 درجة'),
    ('Cámara', 'كاميرا'),
    ('control por voz', 'التحكم الصوتي'),
    ('procesador de 10 núcleos', 'معالج 10 نوى'),
    ('con procesador', 'بمعالج'),
    ('de 16', 'بـ 16'),
    ('de 15', 'بـ 15'),
    ('y 464 W', 'و 464 واط'),
    ('y 705 W', 'و 705 واط'),
    ('10 núcleos', '10 نوى'),
    ('16 altavoces', '16 مكبر صوت'),
    ('15 altavoces', '15 مكبر صوت'),
    ('Sistema de sonido', 'نظام صوت'),
    ('Logic 7', 'لوجيك 7'),
    ('Sistema', 'نظام'),
    ('de sonido', 'صوت'),
    ('10 altavoces', '10 مكبرات صوت'),
    ('Bang & Olufsen Advanced', 'بانغ أند أولوفسن أدفانسد'),
    ('Bang & Olufsen Advanced Sound System', 'بانغ أند أولوفسن أدفانسد ساوند سيستم'),
    ('Advanced Sound System', 'أدفانسد ساوند سيستم'),
    ('Harman Kardon Logic 7', 'هارمان كاردون لوجيك 7'),
    ('Harman Kardon', 'هارمان كاردون'),
    ('BMW OS 8.5 con pantalla curva', 'نظام بي إم دبليو 8.5 بشاشة منحنية'),
    ('con pantalla curva', 'بشاشة منحنية'),
    ('BMW Live Cockpit Professional', 'لوحة بي إم دبليو المهنية'),
    ('BMW Operating System 8.5', 'نظام بي إم دبليو 8.5'),
    ('BMW OS 8.5', 'نظام بي إم دبليو 8.5'),
    ('BMW Intelligent Personal Assistant', 'مساعد بي إم دبليو الشخصي الذكي'),
    ('BMW Digital Key', 'مفتاح بي إم دبليو الرقمي'),
    ('BMW Curved Display', 'شاشة بي إم دبليو المنحنية'),
    ('BMW ConnectedDrive', 'بي إم دبليو كونكتد درايف'),
    ('BMW App', 'تطبيق بي إم دبليو'),
    ('myBMW app', 'تطبيق ماي بي إم دبليو'),
    ('myBMW', 'ماي بي إم دبليو'),
    ('myAudi app', 'تطبيق ماي أودي'),
    ('myAudi', 'ماي أودي'),
    ('Audi Connect', 'أودي كونكت'),
    ('Audi connect', 'أودي كونكت'),
    ('BMW Connected App', 'تطبيق بي إم دبليو كونكتد'),
    ('BMW ConnectedDrive', 'بي إم دبليو كونكتد درايف'),
    ('Apple CarPlay', 'أبل كاربلاي'),
    ('Android Auto', 'أندرويد أوتو'),
    ('Spotify', 'سبوتيفاي'),
    ('Amazon Music', 'أمازون ميوزيك'),
    ('Apple Music', 'أبل ميوزيك'),
    ('Amazon Alexa', 'أليكسا'),
    ('Google Earth', 'جوجل إيرث'),
    ('Netflix', 'نتفليكس'),
    ('YouTube', 'يوتيوب'),
    ('Tidal', 'تايدل'),
    ('Wi-Fi hotspot', 'نقطة اتصال واي فاي'),
    ('Wi-Fi', 'واي فاي'),
    ('Bluetooth 5.0', 'بلوتوث 5.0'),
    ('USB-C', 'يو إس بي-سي'),
    ('USB-A', 'يو إس بي-أي'),
    ('5G', '5 جي'),
    ('4G LTE', '4 جي إل تي إي'),
    ('LTE', 'إل تي إي'),
    ('AMD Ryzen', 'أي إم دي رايزن'),
    ('Qualcomm Snapdragon', 'كوالكوم سناب دراجون'),
    ('NVIDIA Tegra X1', 'إن فيديا تيجرا إكس 1'),
    ('Tesla OS', 'نظام تيسلا'),
    ('Over-the-Air', 'عبر الهواء'),
    ('Tesla App', 'تطبيق تيسلا'),
    ('Autopilot', 'أوتوبايلوت'),
    ('Full Self-Driving', 'القيادة الذاتية الكاملة'),
    ('HEPA', 'هيبا'),
    ('HVAC biocontrol', 'نظام التكييف الحيوي'),
    ('minimalist', 'بسيطة'),
    ('biocontrol', 'تحكم بيولوجي'),
    ('Bose audio', 'نظام صوت بوز'),
    ('Bose', 'بوز'),
    ('Burmester 3D', 'بورميستر 3D'),
    ('Burmester', 'بورميستر'),
    ('Porsche Communication Management', 'نظام بورش للتواصل'),
    ('Porsche InnoDrive', 'نظام بورش إنودرايف'),
    ('Porsche Connect', 'بورش كونكت'),
    ('PCM', 'بي سي إم'),
    ('Wet Mode', 'وضع الرطوبة'),
    ('Sport Response', 'استجابة سبورت'),
    ('Sport Plus', 'سبورت بلس'),
    ('Sport+', 'سبورت بلس'),
    ('Comfort', 'الراحة'),
    ('Sport', 'سبورت'),
    ('Normal', 'عادي'),
    ('Race', 'سباق'),
    ('Launch Control', 'انطلاقة التسارع'),
    ('E Performance', 'إي بيرفورمانس'),
    ('Performance', 'بيرفورمانس'),
    ('48V', '48 فولت'),
    ('400V', '400 فولت'),
    ('12V', '12 فولت'),
    ('AAA games', 'ألعاب الفئة الثلاثية'),
    ('AAA', 'AAA'),
    ('Android', 'أندرويد'),
    ('Automotive', 'أوتوموتيف'),
    ('Bluetooth', 'بلوتوث'),
    ('USB', 'يو إس بي'),
    ('Wi-Fi', 'واي فاي'),
    ('GPS', 'جي بي إس'),
    ('me', 'مي'),
    ('connect', 'كونكت'),
    ('Connect', 'كونكت'),
    ('Safety Shield', 'سيفتي شيلد'),
    ('pre sense', 'بري سينس'),
    ('pre sense front', 'بري سينس أمامي'),
    ('pre sense rear', 'بري سينس خلفي'),
    ('RS torque splitter', 'موزع عزم آر إس'),
    ('torque', 'عزم'),
    ('splitter', 'موزع'),
    ('DQ500', 'دي كيو 500'),
    ('delanteros', 'أمامية'),
    ('cámaras', 'كاميرات'),
    ('laterales', 'جانبية'),
    ('Maxx', 'ماكس'),
    ('spoilers', 'سبويلر'),
    ('Spoiler', 'سبويلر'),
    ('HD', 'عالي الدقة'),
    ('turbo', 'تيربو'),
    ('Turbo', 'تيربو'),
    ('Dynamic', 'ديناميكي'),
    ('Y', 'واي'),
    ('B', 'بي'),
    ('C', 'سي'),
    ('D', 'دي'),
    ('A', 'أي'),
    ('E', 'إي'),
    ('S', 'إس'),
    ('R', 'أر'),
    ('PHEV', 'هجين قابل للشحن'),
    ('Exterior', 'خارجية'),
    ('Driver', 'قيادة'),
    ("Driver's", 'قيادة'),
    ('Bowers', 'باورز'),
    ('Wilkins', 'ويلكينز'),
    ('Escape', 'عادم'),
    ('Frenos', 'فرامل'),
    ('cerámicos', 'سيراميك'),
    ('Pintura', 'طلاء'),
    ('Llantas', 'جنوط'),
    ('Volante', 'دركسون'),
    ('yoke', 'يوك'),
    ('Enganche', 'خطاف'),
    ('remolque', 'سحب'),
    ('Asientos', 'مقاعد'),
    ('traseros', 'خلفية'),
    ('individuales', 'فردية'),
    ('Techo', 'سقف'),
    ('solar', 'شمسي'),
    ('panorámico', 'بانورامي'),
    ('Tapicería', 'تنجيد'),
    ('cuero', 'جلد'),
    ('blanco', 'أبيض'),
    ('créme', 'كريمي'),
    ('delanteros', 'أمامية'),
    ('cámaras', 'كاميرات'),
    ('laterales', 'جانبية'),
    ('NISMO Recaro seats', 'مقاعد ريكارو نيسمو'),
    ('NISMO', 'نيسمو'),
    ('Recaro', 'ريكارو'),
    ('Nappa', 'نابا'),
    ('Vernasca', 'فيرنانسكا'),
    ('Merino', 'ميرينو'),
    ('Valcona', 'فالكونا'),
    ('Dinamica', 'ديناميكا'),
    ('Singleframe', 'سينغل فرايم'),
    ('Godzilla', 'غودزيلا'),
    ('VR38DETT', 'ڤي آر 38 دي إي تي تي'),
    ('GR6', 'جي آر 6'),
    ('T-Hybrid', 'تي هجين'),
    ('mild-hybrid', 'هجين خفيف'),
    ('Mild-hybrid', 'هجين خفيف'),
    ('PHEV', 'هجين قابل للشحن'),
    ('DPF', 'فلتر جسيمات الديزل'),
    ('EGR', 'مبرد العادم'),
    ('CO2', 'ثاني أكسيد الكربون'),
    ('NOx', 'أكسيد النيتروجين'),
    ('OBD', 'أو بي دي'),
    ('OTA', 'عبر الهواء'),
    ('B47', 'بي 47'),
    ('TFSI', 'تي إف إس آي'),
    ('LED Matrix', 'مصابيح ليد ماتريكس'),
    ('Matrix LED', 'ليد ماتريكس'),
    ('High Beam', 'الشعاع العالي'),
    ('DRL', 'أضواء النهار'),
    ('Digital Light', 'الإضاءة الرقمية'),
    ('Head-up display', 'شاشة العرض على الزجاج الأمامي'),
    ('Head-up display opcional', 'شاشة عرض على الزجاج الأمامي اختيارية'),
    ('Cockpit', 'كوكبيت'),
    ('Virtual Cockpit', 'الكوكبيت الافتراضي'),
    ('Virtual Cocklet Plus', 'الكوكبيت الافتراضي بلس'),
    ('Virtual Cockpit Plus', 'الكوكبيت الافتراضي بلس'),
    ('MMI Touch Response', 'إم إم آي تاتش ريسبونس'),
    ('MMI touch response', 'إم إم آي تاتش ريسبونس'),
    ('MMI Touch', 'إم إم آي تاتش'),
    ('MMI Navigation Plus', 'إم إم آي نافيجيشن بلس'),
    ('MMI', 'إم إم آي'),
    ('MBUX Hyperscreen', 'إم بي يو إكس هايبرسكرين'),
    ('MBUX', 'إم بي يو إكس'),
    ('iDrive', 'آي درايف'),
    ('DSG', 'دي إس جي'),
    ('S tronic', 'إس ترونيك'),
    ('S-tronic', 'إس ترونيك'),
    ('Steptronic', 'ستيبترونيك'),
    ('M Steptronic', 'إم ستيبترونيك'),
    ('PDK', 'بي دي كي'),
    ('DCT', 'دي سي تي'),
    ('ZF 8HP', 'زد إف 8 إتش بي'),
    ('IMS bearing', 'تحمل آي إم إس'),
    ('quattro', 'كواترو'),
    ('Quattro', 'كواترو'),
    ('xDrive', 'إكس درايف'),
    ('M xDrive', 'إم إكس درايف'),
    ('4MATIC+', 'فورماتيك بلس'),
    ('4MATIC', 'فورماتيك'),
    ('ATTESA E-TS', 'أتيسا إي-تي-إس'),
    ('ATTESA E-TS AWD', 'نظام الدفع الرباعي أتيسا إي-تي-إس'),
    ('PTM AWD', 'نظام الدفع الرباعي بي تي إم'),
    ('PTM', 'بي تي إم'),
    ('PASM', 'باسم'),
    ('PDCC', 'بي دي سي سي'),
    ('eTurbo', 'إي تيربو'),
    ('T-Hybrid', 'تي هجين'),
    ('RS torque splitter', 'موزع عزم آر إس'),
    ('RS Dynamic Package', 'باقة آر إس ديناميك'),
    ('Dynamic Package', 'باقة ديناميك'),
    ('Bang & Olufsen', 'بانغ أند أولوفسن'),
    ('P Zero', 'بي زيرو'),
    ('P Zero Corsa', 'بي زيرو كورسا'),
    ('Pilot Sport Cup 2', 'بايلوت سبورت كاب 2'),
    ('Pilot Sport 4 S', 'بايلوت سبورت 4 إس'),
    ('Pilot Sport', 'بايلوت سبورت'),
    ('Michelin', 'ميشلان'),
    ('Pirelli', 'بيريلي'),
    ('Continental', 'كونتيننتال'),
    ('Dunlop', 'دنلوب'),
    ('Bridgestone', 'بريدجستون'),
    ('Potenza', 'بوتنزا'),
    ('Potenza Sport', 'بوتنزا سبورت'),
    ('Corsa', 'كورسا'),
    ('SportContact 7', 'سبورت كونتاكت 7'),
    ('SportContact', 'سبورت كونتاكت'),
    ('Brembo', 'بريمبو'),
    ('AMG DYNAMICS', 'ديناميكيات أي إم جي'),
    ('AMG Performance', 'أداء أي إم جي'),
    ('AMG RIDE CONTROL+', 'نظام تحكم أي إم جي في التعليق بلس'),
    ('AMG', 'أي إم جي'),
    ('V8', 'محرك 8 أسطوانات'),
    ('V6', 'محرك 6 أسطوانات'),
    ('R20', '20'),
    ('R21', '21'),
    ('R22', '22'),
    ('R19', '19'),
    ('R18', '18'),
    ('ZR21', '21'),
    ('ZR20', '20'),
    ('ZR22', '22'),
    ('/unidad', 'للإطار'),
    ('VED', 'ضريبة المركبات'),
    ('0-100 km/h', '0-100 كم/س'),
    ('0-100', '0-100'),
    ('km/h', 'كم/س'),
    ('L/100km', 'ل/100 كم'),
    ('L', 'لتر'),
    ('kWh', 'كيلوواط ساعة'),
    ('Nm', 'نيوتن متر'),
    ('HP', 'حصان'),
    ('kW', 'كيلوواط'),
    ('EUR', 'يورو'),
    ('USD', 'دولار'),
    ('GBP', 'جنيه'),
    ('MAD', 'درهم'),
    ('SAR', 'ريال'),
    ('AED', 'درهم'),
    ('TK', 'تي كي'),
    ('km', 'كم'),
    ('meses', 'شهر'),
    ('min', 'دقيقة'),
    ('common', 'شائع'),
    ('occasional', 'متوسط'),
    ('rare', 'نادر'),
    ('buy', 'شراء'),
    ('avoid', 'تجنب'),
    ('consider', 'فكر'),
    ('Carlos M.', 'كارلوس'),
    ('Laura P.', 'لورا'),
    ('Marcus T.', 'ماركوس'),
    ('Sophie L.', 'صوفي'),
    ('Alex R.', 'أليكس'),
    ('Maria G.', 'ماريا'),
    ('Frozen Deep Grey', 'رمادي داكن مطفي'),
    ('Alpine White', 'أبيض ألبي'),
    ('Toronto Red', 'أحمر تورنتو'),
    ('San Marino Blue', 'أزرق سان مارينو'),
    ('Frozen Black', 'أسود مطفي'),
    ('Negro Mythos', 'أسود ميثوس'),
    ('Blanco Ibis', 'أبيض إيبيس'),
    ('Gris Daytona', 'رمادي دايتونا'),
    ('Azul Ascari', 'أزرق أسكاري'),
    ('Rojo Tango', 'أحمر تانغو'),
    ('Verde Sonoma', 'أخضر سونوما'),
    ('Kyalami', 'كيالامي'),
    ('Mythos', 'ميثوس'),
    ('Ibis', 'إيبيس'),
    ('Catalunya', 'كاتالونيا'),
    ('Nardo', 'ناردو'),
    ('Tempest', 'تمبست'),
    ('Arachnid', 'أراكنيد'),
    ('Zero-G', 'زيرو-جي'),
    ('Audi RS3', 'أودي آر إس 3'),
    ('Audi RS7', 'أودي آر إس 7'),
    ('Audi', 'أودي'),
    ('BMW 520d xDrive', 'بي إم دبليو 520d إكس درايف'),
    ('BMW M5 PHEV', 'بي إم دبليو أم 5 هجين'),
    ('BMW M5', 'بي إم دبليو أم 5'),
    ('BMW 520d', 'بي إم دبليو 520d'),
    ('BMW', 'بي إم دبليو'),
    ('Mercedes-AMG GT 63 S E Performance', 'مرسيدس-أي إم جي جي تي 63 إس إي بيرفورمانس'),
    ('Mercedes-AMG GT', 'مرسيدس-أي إم جي جي تي'),
    ('Mercedes-AMG', 'مرسيدس-أي إم جي'),
    ('Mercedes', 'مرسيدس'),
    ('Nissan GT-R NISMO', 'نيسان جي تي آر نيسمو'),
    ('Nissan GT-R', 'نيسان جي تي آر'),
    ('GT-R', 'جي تي آر'),
    ('Nissan', 'نيسان'),
    ('Porsche 911 Turbo S', 'بورش 911 تيربو إس'),
    ('Porsche 911', 'بورش 911'),
    ('Porsche', 'بورش'),
    ('Tesla Model S Plaid', 'تيسلا موديل إس بليد'),
    ('Model S Plaid', 'موديل إس بليد'),
    ('Tesla Model S', 'تيسلا موديل إس'),
    ('Tesla', 'تيسلا'),
    ('Model S', 'موديل إس'),
    ('Plaid', 'بليد'),
    ('M5', 'أم 5'),
    ('RS7', 'آر إس 7'),
    ('RS3', 'آر إس 3'),
    ('A3', 'أي 3'),
    ('A7', 'أي 7'),
    ('A8', 'أي 8'),
    ('Series 7', 'السلسلة 7'),
    ('Series 5', 'السلسلة 5'),
    ('M', 'أم'),
    ('RS', 'آر إس'),
    ('V10', 'محرك 10 أسطوانات'),
    ('V12', 'محرك 12 أسطوانة'),
    (' inline-5', ' 5 أسطوانات'),
    (' inline-6', ' 6 أسطوانات'),
    ('Boxer', 'بوكسر'),
    ('eTorque', 'إي تورك'),
    ('TwinPower Turbo', 'توين باور تيربو'),
    ('Twin-turbo', 'مزدوج التوربين'),
    ('Twin turbo', 'مزدوج التوربين'),
    ('twin turbo', 'مزدوج التوربين'),
    ('biturbo', 'مزدوج التوربين'),
    ('Biturbo', 'مزدوج التوربين'),
    ('supercharged', 'مضغوط'),
    ('Supercharger', 'شاحن فائق'),
    ('supercharged', 'مضغوط'),
    ('Supercharger', 'شاحن فائق'),
    ('AWD', 'دفع رباعي'),
    ('FWD', 'دفع أمامي'),
    ('RWD', 'دفع خلفي'),
    ('PHEV', 'هجين قابل للشحن'),
    ('ICE', 'محرك احتراق داخلي'),
    ('EV', 'سيارة كهربائية'),
    ('SUV', 'سيارة دفع رباعي رياضية'),
    ('Sedan', 'سيدان'),
    ('Coupe', 'كوبيه'),
    ('Station Wagon', 'عائلية'),
    ('Hatchback', 'هاتشباك'),
    ('Fastback', 'فاستباك'),
    ('Gran Turismo', 'جران توريزمو'),
    ('Roadster', 'رودستر'),
    ('Cabriolet', 'كابريوليه'),
    ('Spider', 'سبايدر'),
    ('Targa', 'تارغا'),
    ('Shooting Brake', 'شوتينغ بريك'),
    ('Liftback', 'ليفتباك'),
    ('Crossover', 'كروس أوفر'),
    ('MPV', 'سيارة عائلية متعددة الأغراض'),
    ('Pick-up', 'بيك أب'),
    ('Van', 'فان'),
    ('minivan', 'ميني فان'),
    ('hot hatch', 'هاتشباك رياضية'),
    ('grand tourer', 'جران توريزمو'),
    ('GT', 'جي تي'),
    ('N·m', 'نيوتن متر'),
    ('Nm', 'نيوتن متر'),
    ('kg', 'كجم'),
    ('mm', 'ملم'),
    ('cm', 'سم'),
    ('in', 'بوصة'),
    ('mph', 'ميل/س'),
    ('PS', 'حصان'),
    ('hp', 'حصان'),
    ('rpm', 'د/ق'),
    ('MPGe', 'ميل/غالون كهربائي'),
    ('g/km', 'غرام/كم'),
    ('mg/km', 'ملغ/كم'),
    ('dB', 'ديسيبل'),
    ('V', 'فولت'),
    ('A', 'أمبير'),
    ('Ah', 'أمبير ساعة'),
    ('Wh', 'واط ساعة'),
    ('kW', 'كيلوواط'),
    ('Hz', 'هرتز'),
    ('MPa', 'ميجا باسكال'),
    ('bar', 'بار'),
    ('psi', 'رطل/بوصة مربعة'),
    ('°', 'درجة'),
    ('CVT', 'ناقل حركة متغير باستمرار'),
    ('DCT', 'ناقل حركة مزدوج القابض'),
    ('AT', 'ناقل حركة أوتوماتيكي'),
    ('MT', 'ناقل حركة يدوي'),
    ('AWD', 'دفع رباعي'),
    ('FWD', 'دفع أمامي'),
    ('RWD', 'دفع خلفي'),
    ('4WD', 'دفع رباعي'),
    ('2WD', 'دفع ثنائي'),
    ('4x4', 'دفع رباعي'),
    ('4x2', 'دفع ثنائي'),
    ('ESP', 'نظام الثبات الإلكتروني'),
    ('ABS', 'نظام منع الانغلاق'),
    ('EBD', 'توزيع إلكتروني للفرامل'),
    ('TCS', 'نظام التحكم بالانزلاق'),
    ('TPMS', 'نظام مراقبة ضغط الإطارات'),
    ('LDW', 'تنبيه الخروج عن المسار'),
    ('LKA', 'مساعد حفظ المسار'),
    ('BSW', 'تنبيه النقطة العمياء'),
    ('RCTA', 'تنبيه المرور العرضي الخلفي'),
    ('AEB', 'فرامل الطوارئ التلقائية'),
    ('ACC', 'مثبت السرعة التكيفي'),
    ('HUD', 'شاشة العرض على الزجاج الأمامي'),
    ('ADAS', 'أنظمة مساعدة السائق المتقدمة'),
    ('Lidar', 'ليدار'),
    ('Radar', 'رادار'),
    ('Ultrasonic', 'موجات فوق صوتية'),
    ('Camera', 'كاميرا'),
    ('GPS', 'جي بي إس'),
    ('GLONASS', 'جلوناس'),
    ('Galileo', 'جاليليو'),
    ('BeiDou', 'بيدو'),
    ('CarPlay', 'كاربلاي'),
    ('Android', 'أندرويد'),
    ('Auto', 'أوتو'),
    ('Summons', 'استدعاء'),
    ('Autopark', 'الركن التلقائي'),
    ('Smart Summon', 'استدعاء ذكي'),
    ('FSD', 'القيادة الذاتية الكاملة'),
    ('FSD Beta', 'القيادة الذاتية الكاملة بيتا'),
    ('Enhanced Autopilot', 'أوتوبايلوت محسّن'),
    ('Traffic-Aware Cruise Control', 'مثبت سرعة متنبّه بالحركة المرورية'),
    ('Navigate on Autopilot', 'الملاحة على أوتوبايلوت'),
    ('Auto Lane Change', 'تغيير المسار التلقائي'),
    ('Autosteer', 'التوجيه التلقائي'),
    ('Highway', 'الطريق السريع'),
    ('City Streets', 'شوارع المدينة'),
    ('Traffic Light', 'إشارة المرور'),
    ('Stop Sign', 'توقف'),
    ('Roundabout', 'دوار'),
    ('Intersection', 'تقاطع'),
    ('Pedestrian', 'مشاة'),
    ('Cyclist', 'دراجون'),
    ('Vehicle', 'مركبة'),
    ('Lane', 'مسار'),
    ('Sign', 'إشارة'),
    ('Speed Limit', 'حد السرعة'),
    ('School Zone', 'منطقة مدرسة'),
    ('Work Zone', 'منطقة أعمال'),
    ('Railway', 'سكة حديد'),
    ('Tunnel', 'نفق'),
    ('Bridge', 'جسر'),
    ('Parking', 'ركن'),
    ('Garage', 'مرآب'),
    ('Driveway', 'مدخل السيارة'),
    ('Motorway', 'طريق سريع'),
    ('Highway', 'طريق سريع'),
    ('Dual carriageway', 'طريق مزدوج'),
    ('Single carriageway', 'طريق مفرد'),
    ('Urban', 'حضري'),
    ('Rural', 'ريفي'),
    ('Off-road', 'خارج الطريق'),
    ('Track', 'حلبة'),
    ('Drag', 'سباق تسارع'),
    ('Drift', 'انزلاق'),
    ('Cruise', 'قيادة cruising'),
    ('Eco', 'اقتصادي'),
    ('Save', 'حفظ'),
    ('Range', 'مدى'),
    ('Hold', 'إمساك'),
    ('Regen', 'استرداد الطاقة'),
    ('Lift', 'رفع'),
    ('Lower', 'خفض'),
    ('Air suspension', 'تعليق هوائي'),
    ('Adaptive damping', 'مخمدات تكيفية'),
    ('Active roll', 'تثبيت نشط للانقلاب'),
    ('Rear-wheel steering', 'توجيه العجلات الخلفية'),
    ('Torque vectoring', 'موجه العزم'),
    ('Electronic diff', 'دفرنسيال إلكتروني'),
    ('Mechanical diff', 'دفرنسيال ميكانيكي'),
    ('Limited-slip diff', 'دفرنسيال محدود الانزلاق'),
    ('Open diff', 'دفرنسيال مفتوح'),
    ('Locking diff', 'دفرنسيال قفل'),
    ('Center diff', 'دفرنسيال مركزي'),
    ('Transfer case', 'علبة نقل الحركة'),
    ('Propeller shaft', 'عمود الدوران'),
    ('Driveshaft', 'عمود الدوران'),
    ('CV joint', 'مفصل كونستانت فيلوسيتي'),
    ('Universal joint', 'مفصل عالمي'),
    ('Differential', 'دفرنسيال'),
    ('Final drive', 'التروس النهائية'),
    ('Gearbox', 'علبة التروس'),
    ('Transmission', 'ناقل الحركة'),
    ('Clutch', 'قابض'),
    ('Flywheel', 'عجلة الطيران'),
    ('Torque converter', 'محول العزم'),
    ('Driveshaft', 'عمود الدوران'),
    ('Axle', 'محور'),
    ('Hub', 'محور العجلة'),
    ('Bearing', 'تحمل'),
    ('Bush', 'بوش'),
    ('Ball joint', 'مفصل كروي'),
    ('Tie rod', 'قضيب توجيه'),
    ('Steering rack', 'منظمة التوجيه'),
    ('Power steering', 'توجيه معزز'),
    ('Electric steering', 'توجيه كهربائي'),
    ('Hydraulic steering', 'توجيه هيدروليكي'),
    ('Rack and pinion', 'منظمة التوجيه'),
    ('MacPherson strut', 'مخمد ماكفرسون'),
    ('Multi-link', 'تعليق متعدد الوصلات'),
    ('Double wishbone', 'تعليق مزدوج المثلث'),
    ('Torsion beam', 'عمود التواء'),
    ('Leaf spring', 'زنبرك ليفي'),
    ('Coil spring', 'زنبرك لولبي'),
    ('Air spring', 'زنبرك هوائي'),
    ('Active suspension', 'تعليق نشط'),
    ('Semi-active suspension', 'تعليق شبه نشط'),
    ('Passive suspension', 'تعليق سلبي'),
    ('Magnetic ride', 'تعليق مغناطيسي'),
    ('Hydraulic suspension', 'تعليق هيدروليكي'),
    ('Active anti-roll', 'تثبيت نشط للانقلاب'),
    ('Subframe', 'إطار فرعي'),
    ('Unibody', 'هيكل أحادي'),
    ('Body-on-frame', 'هيكل على إطار'),
    ('Monocoque', 'هيكل أحادي'),
    ('Space frame', 'إطار فضائي'),
    ('Exoskeleton', 'هيكل خارجي'),
    ('Crumple zone', 'منطقة تشوه'),
    ('Side impact beam', 'عريضة جانبية للصدمات'),
    ('Roll cage', 'قفص حماية'),
    ('Firewall', 'جدار ناري'),
    ('Floor pan', 'أرضية الهيكل'),
    ('Roof', 'سقف'),
    ('Pillars', 'أعمدة'),
    ('A-pillar', 'عمود A'),
    ('B-pillar', 'عمود B'),
    ('C-pillar', 'عمود C'),
    ('D-pillar', 'عمود D'),
    ('Hood', 'غطاء المحرك'),
    ('Bonnet', 'غطاء المحرك'),
    ('Trunk', 'صندوق خلفي'),
    ('Boot', 'صندوق خلفي'),
    ('Frunk', 'صندوق أمامي'),
    ('Tailgate', 'باب خلفي'),
    ('Liftgate', 'باب خلفي رافع'),
    ('Gullwing', 'أبواب جناحية'),
    ('Scissor doors', 'أبواب مقصية'),
    ('Suicide doors', 'أبواب انتحارية'),
    ('Sliding doors', 'أبواب منزلقة'),
    ('Panoramic roof', 'سقف بانورامي'),
    ('Sunroof', 'سقف شمسي'),
    ('Moonroof', 'سقف قمري'),
    ('Convertible', 'كابريوليه'),
    ('Hardtop', 'سقف صلب'),
    ('Soft top', 'سقف قماشي'),
    ('T-top', 'سقف T'),
    ('Targa top', 'سقف تارغا'),
    ('Canvas', 'قماش'),
    ('Vinyl', 'فينيل'),
    ('Leather', 'جلد'),
    ('Alcantara', 'ألكانتارا'),
    ('Suede', 'شمواه'),
    ('Microfiber', 'ألياف دقيقة'),
    ('Carbon fiber', 'ألياف كربون'),
    ('Forged carbon', 'كربون مزور'),
    ('Fiberglass', 'ألياف زجاجية'),
    ('Kevlar', 'كيفلار'),
    ('Aluminum', 'ألومنيوم'),
    ('Magnesium', 'مغنيسيوم'),
    ('Titanium', 'تيتانيوم'),
    ('Steel', 'فولاذ'),
    ('Stainless steel', 'فولاذ مقاوم للصدأ'),
    ('High-strength steel', 'فولاذ عالي القوة'),
    ('Ultra-high-strength steel', 'فولاذ فائق القوة'),
    ('Boron steel', 'فولاذ بورون'),
    ('Alloy', 'سبيكة'),
    ('Composite', 'مواد مركبة'),
    ('Plastic', 'بلاستيك'),
    ('Rubber', 'مطاط'),
    ('Glass', 'زجاج'),
    ('Polycarbonate', 'بولي كربونات'),
    ('Acrylic', 'أكريليك'),
    ('Paint', 'طلاء'),
    ('Clear coat', 'طبقة شفافة'),
    ('Primer', 'طبقة أساس'),
    ('Base coat', 'الطبقة الأساسية'),
    ('Pearl coat', 'طبقة لؤلؤية'),
    ('Metallic paint', 'طلاء معدني'),
    ('Matte paint', 'طلاء مطفي'),
    ('Gloss paint', 'طلاء لامع'),
    ('Ceramic coating', 'طلاء سيراميك'),
    ('PPF', 'حماية طلاء'),
    ('Vinyl wrap', 'تغليف فينيل'),
    ('Chrome', 'كروم'),
    ('Black chrome', 'كروم أسود'),
    ('Anodized', 'مؤكسد'),
    ('Brushed', 'مصقول'),
    ('Polished', 'ملمع'),
    ('Satin', 'ساتان'),
    ('Matte', 'مطفي'),
    ('Gloss', 'لامع'),
    ('Metallic', 'معدني'),
    ('Pearl', 'لؤلؤي'),
    ('Solid', 'صلب'),
    ('Frozen', 'مطفي'),
    ('Velvet', 'مخمل'),
    ('Silk', 'حرير'),
    ('Wool', 'صوف'),
    ('Linen', 'كتان'),
    ('Cotton', 'قطن'),
    ('Synthetic', 'اصطناعي'),
    ('Natural', 'طبيعي'),
    ('Vegan', 'نباتي'),
    ('Recycled', 'معاد تدويره'),
    ('Organic', 'عضوي'),
    ('Sustainable', 'مستدام'),
    ('Eco-friendly', 'صديق للبيئة'),
    ('Biodegradable', 'قابل للتحلل'),
    ('Non-toxic', 'غير سام'),
    ('Hypoallergenic', 'منخفض الحساسية'),
    ('Antibacterial', 'مضاد للبكتيريا'),
    ('Odor-resistant', 'مقاوم للروائح'),
    ('Water-resistant', 'مقاوم للماء'),
    ('Stain-resistant', 'مقاوم للبقع'),
    ('UV-resistant', 'مقاوم للأشعة فوق البنفسجية'),
    ('Scratch-resistant', 'مقاوم للخدوش'),
    ('Impact-resistant', 'مقاوم للصدمات'),
    ('Heat-resistant', 'مقاوم للحرارة'),
    ('Fire-resistant', 'مقاوم للحريق'),
    ('Electrically conductive', 'موصل كهربائياً'),
    ('Thermally conductive', 'موصل حرارياً'),
    ('Insulating', 'عازل'),
    ('Magnetic', 'مغناطيسي'),
    ('Non-magnetic', 'غير مغناطيسي'),
    ('Radio-opaque', 'معتم للأشعة'),
    ('X-ray transparent', 'شفاف للأشعة السينية'),
    ('Acoustic', 'صوتي'),
    ('Soundproof', 'عازل للصوت'),
    ('Vibration-dampening', 'مخمد للاهتزازات'),
    ('Shock-absorbing', 'ممتص للصدمات'),
    ('Energy-absorbing', 'ممتص للطاقة'),
    ('Self-healing', 'ذاتي الشفاء'),
    ('Self-cleaning', 'ذاتي التنظيف'),
    ('Anti-fog', 'مضاد للضباب'),
    ('Anti-glare', 'مضاد للوهج'),
    ('Anti-reflective', 'مضاد للانعكاس'),
    ('Hydrophobic', 'كره الماء'),
    ('Oleophobic', 'كره الزيوت'),
    ('Anti-static', 'مضاد للكهرباء الساكنة'),
    ('Conductive coating', 'طلاء موصل'),
    ('Thermal coating', 'طلاء حراري'),
    ('Protective coating', 'طلاء وقائي'),
    ('Anti-corrosion', 'مضاد للتآكل'),
    ('Galvanized', 'مجلفن'),
    ('Anodized aluminum', 'ألومنيوم مؤكسد'),
    ('Powder-coated', 'طلاء مسحوق'),
    ('Electroplated', 'طلاء كهربائي'),
    ('Polished aluminum', 'ألومنيوم مصقول'),
    ('Brushed aluminum', 'ألومنيوم مصقول'),
    ('Satin aluminum', 'ألومنيوم ساتان'),
    ('Black aluminum', 'ألومنيوم أسود'),
    ('Silver aluminum', 'ألومنيوم فضي'),
    ('Gold aluminum', 'ألومنيوم ذهبي'),
    ('Red aluminum', 'ألومنيوم أحمر'),
    ('Blue aluminum', 'ألومنيوم أزرق'),
    ('Green aluminum', 'ألومنيوم أخضر'),
    ('Yellow aluminum', 'ألومنيوم أصفر'),
    ('Orange aluminum', 'ألومنيوم برتقالي'),
    ('Purple aluminum', 'ألومنيوم بنفسجي'),
    ('White aluminum', 'ألومنيوم أبيض'),
    ('Grey aluminum', 'ألومنيوم رمادي'),
    ('Brown aluminum', 'ألومنيوم بني'),
    ('Pink aluminum', 'ألومنيوم وردي'),
    ('Turquoise aluminum', 'ألومنيوم فيروزي'),
    ('Beige aluminum', 'ألومنيوم بيج'),
    ('Ivory aluminum', 'ألومنيوم عاجي'),
    ('Cream aluminum', 'ألومنيوم كريمي'),
    ('Champagne aluminum', 'ألومنيوم شامبانيا'),
    ('Bronze aluminum', 'ألومنيوم برونزي'),
    ('Copper aluminum', 'ألومنيوم نحاسي'),
    ('Rose gold aluminum', 'ألومنيوم ذهبي وردي'),
    ('Platinum aluminum', 'ألومنيوم بلاتيني'),
    ('Titanium aluminum', 'ألومنيوم تيتانيومي'),
    ('Carbon aluminum', 'ألومنيوم كربوني'),
    ('Forged aluminum', 'ألومنيوم مزور'),
    ('Cast aluminum', 'ألومنيوم مسبوك'),
    ('Extruded aluminum', 'ألومنيوم بثق'),
    ('Wrought aluminum', 'ألومنيوم مطروق'),
    ('Anodized steel', 'فولاذ مؤكسد'),
    ('Stainless steel', 'فولاذ مقاوم للصدأ'),
    ('Galvanized steel', 'فولاذ مجلفن'),
    ('Carbon steel', 'فولاذ كربوني'),
    ('Tool steel', 'فولاذ أدوات'),
    ('Spring steel', 'فولاذ زنبركي'),
    ('Bearing steel', 'فولاذ تحمل'),
    ('Case-hardened steel', 'فولاذ مصلب السطح'),
    ('Through-hardened steel', 'فولاذ مصلب بالكامل'),
    ('Tempered steel', 'فولاذ معالج حرارياً'),
    ('Quenched steel', 'فولاذ مُقسى'),
    ('Annealed steel', 'فولاذ مُلدن'),
    ('Normalized steel', 'فولاذ مُطبيع'),
    ('Maraging steel', 'فولاذ مارتنزيتي'),
    ('Hadfield steel', 'فولاذ هادفيلد'),
    ('Damascus steel', 'فولاذ دمشقي'),
    ('Pattern-welded steel', 'فولاذ ملحوم بنمط'),
    ('Crucible steel', 'فولاذ بوتقة'),
    ('Bloomery steel', 'فولاذ فرن الإختزال'),
    ('Wootz steel', 'فولاذ ووتز'),
    ('Bulat steel', 'فولاذ بُلات'),
    ('Norickel', 'نورنيكل'),
    ('Inconel', 'إنكونيل'),
    ('Hastelloy', 'هاستيلوي'),
    ('Monel', 'مونيل'),
    ('Incoloy', 'إنكولوي'),
    ('Stellite', 'ستيلايت'),
    ('Titanium alloy', 'سبيكة تيتانيوم'),
    ('Magnesium alloy', 'سبيكة مغنيسيوم'),
    ('Zinc alloy', 'سبيكة زنك'),
    ('Brass', 'نحاس أصفر'),
    ('Bronze', 'برونز'),
    ('Copper', 'نحاس'),
    ('Nickel', 'نيكل'),
    ('Tin', 'قصدير'),
    ('Lead', 'رصاص'),
    ('Zinc', 'زنك'),
    ('Cadmium', 'كادميوم'),
    ('Chromium', 'كروم'),
    ('Manganese', 'منغنيز'),
    ('Silicon', 'سليكون'),
    ('Phosphorus', 'فوسفور'),
    ('Sulfur', 'كبريت'),
    ('Boron', 'بورون'),
    ('Carbon', 'كربون'),
    ('Nitrogen', 'نيتروجين'),
    ('Oxygen', 'أكسجين'),
    ('Hydrogen', 'هيدروجين'),
    ('Helium', 'هيليوم'),
    ('Lithium', 'ليثيوم'),
    ('Beryllium', 'بيريليوم'),
    ('Sodium', 'صوديوم'),
    ('Potassium', 'بوتاسيوم'),
    ('Calcium', 'كالسيوم'),
    ('Magnesium', 'مغنيسيوم'),
    ('Iron', 'حديد'),
    ('Cobalt', 'كوبالت'),
    ('Nickel', 'نيكل'),
    ('Copper', 'نحاس'),
    ('Zinc', 'زنك'),
    ('Gallium', 'جاليوم'),
    ('Germanium', 'جرمانيوم'),
    ('Arsenic', 'زرنيخ'),
    ('Selenium', 'سيلينيوم'),
    ('Bromine', 'بروم'),
    ('Krypton', 'كريبتون'),
    ('Rubidium', 'روبيديوم'),
    ('Strontium', 'سترونتيوم'),
    ('Yttrium', 'إتريوم'),
    ('Zirconium', 'زركونيوم'),
    ('Niobium', 'نيوبيوم'),
    ('Molybdenum', 'موليبدينوم'),
    ('Technetium', 'تكتيشيوم'),
    ('Ruthenium', 'روثينيوم'),
    ('Rhodium', 'روديوم'),
    ('Palladium', 'بالاديوم'),
    ('Silver', 'فضة'),
    ('Cadmium', 'كادميوم'),
    ('Indium', 'إنديوم'),
    ('Tin', 'قصدير'),
    ('Antimony', 'إنتيموني'),
    ('Tellurium', 'تيلوريوم'),
    ('Iodine', 'يود'),
    ('Xenon', 'زينون'),
    ('Cesium', 'سيزيوم'),
    ('Barium', 'باريوم'),
    ('Lanthanum', 'لانثانوم'),
    ('Cerium', 'سيريوم'),
    ('Praseodymium', 'براسيوديميوم'),
    ('Neodymium', 'نيوديميوم'),
    ('Promethium', 'بروميثيوم'),
    ('Samarium', 'ساماريوم'),
    ('Europium', 'يوروبيوم'),
    ('Gadolinium', 'جادولينيوم'),
    ('Terbium', 'تيربيوم'),
    ('Dysprosium', 'ديسبروسيوم'),
    ('Holmium', 'هولميوم'),
    ('Erbium', 'إربيوم'),
    ('Thulium', 'ثوليوم'),
    ('Ytterbium', 'إيتربيوم'),
    ('Lutetium', 'لوتيشيوم'),
    ('Hafnium', 'هافنيوم'),
    ('Tantalum', 'تانتالوم'),
    ('Tungsten', 'تنغستن'),
    ('Rhenium', 'رينيوم'),
    ('Osmium', 'أوزميوم'),
    ('Iridium', 'إيريديوم'),
    ('Platinum', 'بلاتين'),
    ('Gold', 'ذهب'),
    ('Mercury', 'زئبق'),
    ('Thallium', 'ثاليوم'),
    ('Lead', 'رصاص'),
    ('Bismuth', 'بزموت'),
    ('Polonium', 'بولونيوم'),
    ('Astatine', 'أستاتين'),
    ('Radon', 'رادون'),
    ('Francium', 'فرانسيوم'),
    ('Radium', 'راديوم'),
    ('Actinium', 'اكتينيوم'),
    ('Thorium', 'ثوريوم'),
    ('Protactinium', 'بروتكتينيوم'),
    ('Uranium', 'يورانيوم'),
    ('Neptunium', 'نبتونيوم'),
    ('Plutonium', 'بلوتونيوم'),
    ('Americium', 'أمريكيوم'),
    ('Curium', 'كوريوم'),
    ('Berkelium', 'بركيليوم'),
    ('Californium', 'كاليفورنيوم'),
    ('Einsteinium', 'أينشتاينيوم'),
    ('Fermium', 'فيرميوم'),
    ('Mendelevium', 'مندليفيوم'),
    ('Nobelium', 'نوبيليوم'),
    ('Lawrencium', 'لورنسيوم'),
    ('Rutherfordium', 'رذرفورديوم'),
    ('Dubnium', 'دوبنيوم'),
    ('Seaborgium', 'سيبورجيوم'),
    ('Bohrium', 'بوريوم'),
    ('Hassium', 'هاسيوم'),
    ('Meitnerium', 'مايتنيريوم'),
    ('Darmstadtium', 'دارمشتاتيوم'),
    ('Roentgenium', 'رونتغينيوم'),
    ('Copernicium', 'كوبرنيسيوم'),
    ('Nihonium', 'نيهونيوم'),
    ('Flerovium', 'فليروفيوم'),
    ('Moscovium', 'موسكوفيوم'),
    ('Livermorium', 'ليفيرموريوم'),
    ('Tennessine', 'تينيسين'),
    ('Oganesson', 'أوغانيسون'),
    ('metallic', 'معدني'),
    ('solid', 'صلب'),
    ('pearl', 'لؤلؤي'),
    ('matte', 'مطفي'),
    ('gloss', 'لامع'),
    ('satin', 'ساتان'),
    ('frozen', 'مطفي'),
    ('comfort', 'راحة'),
    ('sport', 'رياضي'),
    ('performance', 'أداء'),
    ('materials', 'مواد'),
    ('audio', 'صوت'),
    ('technology', 'تقنية'),
    ('light', 'إضاءة'),
    ('seat', 'مقعد'),
    ('screen', 'شاشة'),
    ('sound', 'صوت'),
    # Additional terms from audit
    ('LED', 'ليد'),
    ('ISOFIX', 'نظام تثبيت مقاعد الأطفال'),
    ('Virtual', 'افتراضي'),
    ('OS', 'أو إس'),
    ('Hi-Fi', 'هاي فاي'),
    ('Android Automotive', 'أندرويد أوتوموتيف'),
    ('Distronic Plus', 'ديسترونيك بلس'),
    ('Stop & Go', 'توقف وانطلاق'),
    ('Mercedes me connect', 'مرسيدس مي كونكت'),
    ('Mercedes me', 'مرسيدس مي'),
    ('AC', 'تيار متردد'),
    ('DC', 'تيار مستمر'),
    ('Panamericana', 'بان أمريكانا'),
    ('Hyperscreen', 'هايبرسكرين'),
    ('3D', 'ثلاثي الأبعاد'),
    ('J', 'ج'),
    ('Nissan Connect', 'نيسان كونكت'),
    ('Nissan Safety Shield 360', 'نيسان سيفتي شيلد 360'),
    ('Premium', 'ممتاز'),
    ('Curved Display', 'شاشة منحنية'),
    ('Spoiler', 'سبويلر'),
    ('Taycan', 'تايكان'),
    ('launch control', 'انطلاق التسارع'),
    ('Auto Park', 'الركن التلقائي'),
    ('Summon', 'استدعاء'),
    ('Linux', 'لينكس'),
    ('superior', 'علوي'),
    ('inferior', 'سفلي'),
    ('con', 'مع'),
    ('Exhaust', 'عادم'),
    ('Ceramic Brakes', 'فرامل سيراميك'),
    ('Ceramic', 'سيراميك'),
    ('Brakes', 'فرامل'),
    ('Headlights', 'مصابيح أمامية'),
    ('Headlight', 'مصباح أمامي'),
    ('Full leather', 'جلد كامل'),
    ('Full جلد Interior', 'داخلية جلد كاملة'),
    ('Interior', 'داخلية'),
    ('Asientos traseros', 'مقاعد خلفية'),
    ('Asientos', 'مقاعد'),
    ('traseros', 'خلفية'),
    ('Techo solar panorámico', 'سقف بانورامي'),
    ('Techo solar', 'سقف شمسي'),
    ('panorámico', 'بانورامي'),
    ('Frenos M Sport', 'فرامل أم سبورت'),
    ('Frenos', 'فرامل'),
    ('Tapicería de cuero', 'تنجيد جلدي'),
    ('Tapicería', 'تنجيد'),
    ('cuero', 'جلد'),
    ('Bowers & Wilkins Diamond', 'باورز آند ويلكينز دايموند'),
    ('Bowers & Wilkins', 'باورز آند ويلكينز'),
    ('M Shadow Line', 'خط أم شادو'),
    ('Shadow Line', 'خط شادو'),
    ('Frenos cerámicos', 'فرامل سيراميك'),
    ('cerámicos', 'سيراميك'),
    ('Interior carbon / Valcona', 'داخلية كربون / فالكونا'),
    ('Asientos traseros individuales', 'مقاعد خلفية فردية'),
    ('individuales', 'فردية'),
    ('Pintura premium', 'طلاء ممتاز'),
    ('Pintura', 'طلاء'),
    ('Llantas 21', 'جنوط 21 بوصة'),
    ('Llantas', 'جنوط'),
    ('Interior blanco/créme', 'داخلية بيضاء/كريمية'),
    ('blanco', 'أبيض'),
    ('créme', 'كريمي'),
    ('Volante yoke', 'دركسون يوك'),
    ('Volante', 'دركسون'),
    ('yoke', 'يوك'),
    ('Enganche de remolque', 'خطاف سحب'),
    ('Enganche', 'خطاف'),
    ('remolque', 'سحب'),
    ('Laser', 'ليزر'),
    ('Matrix LED', 'ليد ماتريكس'),
    ('Comfort Package', 'باقة الراحة'),
    ('Tech Package', 'باقة التقنية'),
    ("M Driver's Package", 'باقة قيادة أم'),
    ('M Carbon Ceramic Brakes', 'فرامل سيراميك كربون أم'),
    ('M Carbon Exterior Package', 'باقة خارجية كربون أم'),
    ('RS Sport Exhaust', 'عادم آر إس سبورت'),
    ('RS Ceramic Brakes', 'فرامل سيراميك آر إس'),
    ('Matrix LED Headlights', 'مصابيح ليد ماتريكس'),
    ('Full Self-Driving', 'القيادة الذاتية الكاملة'),
    ('M Driver\'s Package', 'باقة قيادة أم'),
    ('M Carbon Ceramic Brakes', 'فرامل سيراميك كربون أم'),
    ('M Carbon Exterior Package', 'باقة خارجية كربون أم'),
    ('M Sport Exhaust', 'عادم أم سبورت'),
    ('M Sport Brakes', 'فرامل أم سبورت'),
    ('M Shadow Line', 'خط أم شادو'),
    ('RS Sport Exhaust', 'عادم آر إس سبورت'),
    ('RS Ceramic Brakes', 'فرامل سيراميك آر إس'),
    ('RS Dynamic Package Plus', 'باقة آر إس ديناميك بلس'),
    ('RS Dynamic Package', 'باقة آر إس ديناميك'),
    ('Matrix LED Headlights', 'مصابيح ليد ماتريكس'),
    ('LED Matrix / Laser', 'ليد ماتريكس / ليزر'),
    ('Full leather Interior', 'داخلية جلد كاملة'),
    ('Comfort Package', 'باقة الراحة'),
    ('Tech Package', 'باقة التقنية'),
    ('Bowers & Wilkins Diamond', 'باورز آند ويلكينز دايموند'),
    ('Frenos M Sport', 'فرامل أم سبورت'),
    ('Frenos cerámicos', 'فرامل سيراميك'),
    ('Tapicería de cuero', 'تنجيد جلدي'),
    ('Asientos traseros individuales', 'مقاعد خلفية فردية'),
    ('Asientos traseros', 'مقاعد خلفية'),
    ('Techo solar panorámico', 'سقف بانورامي'),
    ('Pintura premium', 'طلاء ممتاز'),
    ('Llantas 21', 'جنوط 21 بوصة'),
    ('Interior blanco/créme', 'داخلية بيضاء/كريمية'),
    ('Volante yoke', 'دركسون يوك'),
    ('Enganche de remolque', 'خطاف سحب'),
    ('Auto Lane Change', 'تغيير المسار التلقائي'),
    ('Autosteer', 'التوجيه التلقائي'),
    ('Traffic-Aware Cruise Control', 'مثبت سرعة متنبّه بالحركة المرورية'),
    ('Navigate on Autopilot', 'الملاحة على أوتوبايلوت'),
    ('Enhanced Autopilot', 'أوتوبايلوت محسّن'),
    ('Smart Summon', 'استدعاء ذكي'),
    ('Porsche 911', 'بورش 911'),
    ('Porsche', 'بورش'),
    ('Tesla', 'تيسلا'),
    ('Nissan', 'نيسان'),
    ('BMW', 'بي إم دبليو'),
    ('Audi', 'أودي'),
    ('Mercedes', 'مرسيدس'),
    ('AMG', 'أي إم جي'),
    ('GT', 'جي تي'),
    ('RS', 'آر إس'),
    ('M', 'أم'),
    ('R', 'أر'),
    ('S', 'إس'),
    ('PHEV', 'هجين قابل للشحن'),
    ('SUV', 'سيارة دفع رباعي رياضية'),
    ('CO2', 'ثاني أكسيد الكربون'),
    ('NOx', 'أكسيد النيتروجين'),
    ('px', 'بكسل'),
    ('x', '×'),
    ('RON', 'أوكتان'),
    ('VED', 'ضريبة المركبات'),
    ('M Sport', 'أم سبورت'),
    ('X Line', 'إكس لاين'),
    ('Luxury Line', 'خط فاخر'),
    ('Executive Package', 'باقة تنفيذية'),
    ('Cold Weather Package', 'باقة الطقس البارد'),
    ('Driving Assistant Professional', 'مساعد القيادة المحترف'),
    ('Parking Assistant Plus', 'مساعد الركن بلس'),
    ('Lane Departure Warning', 'تنبيه الخروج عن المسار'),
    ('Audi pre sense front', 'أودي بري سينس أمامي'),
    ('Audi pre sense rear', 'أودي بري سينس خلفي'),
    ('Start-Stop', 'توقف وانطلاق'),
    ('Run-flat', 'إطارات بدون إنفجار'),
    ('All-season', 'كل المواسم'),
    ('Summer', 'صيفي'),
    ('Winter', 'شتوي'),
    ('Sound', 'صوت'),
    ('System', 'نظام'),
    ('Plus', 'بلس'),
    ('Package', 'باقة'),
    ('Edition', 'إصدار'),
    ('Carbon', 'كربون'),
    ('Diamond', 'دايموند'),
    ('Comfort', 'راحة'),
    ('Technology', 'تقنية'),
    ('Sportback', 'سبورتباك'),
    ('Cabriolet', 'كابريوليه'),
    ('Coupe', 'كوبيه'),
    ('Sedan', 'سيدان'),
    ('Wagon', 'عائلية'),
    ('Avant', 'أفانت'),
    ('Allroad', 'أول رود'),
    ('Quattro', 'كواترو'),
    ('TFSI', 'تي إف إس آي'),
    ('TDI', 'تي دي آي'),
    ('e-tron', 'إي-ترون'),
    ('MHEV', 'هجين خفيف'),
    ('PHEV', 'هجين قابل للشحن'),
    ('BEV', 'سيارة كهربائية بالكامل'),
    ('ICE', 'محرك احتراق داخلي'),
    ('HEV', 'هجين'),
    ('MPG', 'ميل/غالون'),
    ('MPGe', 'ميل/غالون كهربائي'),
    ('km', 'كم'),
    ('L', 'لتر'),
    ('kW', 'كيلوواط'),
    ('kWh', 'كيلوواط ساعة'),
    ('Nm', 'نيوتن متر'),
    ('HP', 'حصان'),
    ('PS', 'حصان'),
    ('mph', 'ميل/س'),
    ('kg', 'كجم'),
    ('mm', 'ملم'),
    ('cm', 'سم'),
    ('in', 'بوصة'),
    ('rpm', 'د/ق'),
    ('dB', 'ديسيبل'),
    ('V', 'فولت'),
    ('A', 'أمبير'),
    ('Ah', 'أمبير ساعة'),
    ('Wh', 'واط ساعة'),
    ('Hz', 'هرتز'),
    ('MPa', 'ميجا باسكال'),
    ('bar', 'بار'),
    ('psi', 'رطل/بوصة مربعة'),
    ('°', 'درجة'),
    ('CVT', 'ناقل حركة متغير باستمرار'),
    ('DCT', 'ناقل حركة مزدوج القابض'),
    ('AT', 'ناقل حركة أوتوماتيكي'),
    ('MT', 'ناقل حركة يدوي'),
    ('FWD', 'دفع أمامي'),
    ('RWD', 'دفع خلفي'),
    ('4WD', 'دفع رباعي'),
    ('2WD', 'دفع ثنائي'),
    ('4x4', 'دفع رباعي'),
    ('ESP', 'نظام الثبات الإلكتروني'),
    ('ABS', 'نظام منع الانغلاق'),
    ('EBD', 'توزيع إلكتروني للفرامل'),
    ('TCS', 'نظام التحكم بالانزلاق'),
    ('TPMS', 'نظام مراقبة ضغط الإطارات'),
    ('LDW', 'تنبيه الخروج عن المسار'),
    ('LKA', 'مساعد حفظ المسار'),
    ('BSW', 'تنبيه النقطة العمياء'),
    ('RCTA', 'تنبيه المرور العرضي الخلفي'),
    ('AEB', 'فرامل الطوارئ التلقائية'),
    ('ACC', 'مثبت السرعة التكيفي'),
    ('HUD', 'شاشة العرض على الزجاج الأمامي'),
    ('ADAS', 'أنظمة مساعدة السائق المتقدمة'),
    # Missing terms from latest audit
    ('Assistant', 'مساعد'),
    ('Driving', 'قيادة'),
    ('Parking', 'ركن'),
    ('Lane', 'مسار'),
    ('Departure', 'خروج'),
    ('Warning', 'تحذير'),
    ('Driving Assistant Professional', 'مساعد القيادة المحترف'),
    ('Parking Assistant Plus', 'مساعد الركن بلس'),
    ('Lane Departure Warning', 'تنبيه الخروج عن المسار'),
    ('Audi pre sense front', 'أودي بري سينس أمامي'),
    ('Audi pre sense rear', 'أودي بري سينس خلفي'),
    ('Grupo', 'المجموعة'),
    ('máximo', 'الحد الأقصى'),
    ('Grupo 20 (máximo)', 'المجموعة 20 (الحد الأقصى)'),
    ('Aproximadamente', 'حوالي'),
    ('año', 'سنة'),
    ('en función de', 'حسب'),
    ('la comunidad autónoma', 'المجتمع الذاتي'),
    ('Aproximadamente 700 €/año en función de la comunidad autónoma', 'حوالي 700 يورو/سنة حسب المجتمع الذاتي'),
    ('base', 'أساس'),
    ('siguientes', 'التالية'),
    ('£2.745 año base, £600 siguientes años', '2.745 جنيه سنة أساس، 600 جنيه سنوات لاحقة'),
    ('Gasolina', 'بنزين'),
    ('carga', 'شحن'),
    ('eléctrica', 'كهربائي'),
    ('Gasolina 98 RON / carga eléctrica', 'بنزين 98 أوكتان / شحن كهربائي'),
    ('TK', 'تي كي'),
    ('SP', 'إس بي'),
    ('Park', 'ركن'),
    ('P Zero', 'بي زيرو'),
    ('Pilot Sport 4S', 'بايلوت سبورت 4 إس'),
    ('Dunlop SP Sport Maxx', 'دنلوب إس بي سبورت ماكس'),
    ('AAA', 'الفئة الثلاثية'),
    ('Run-flat', 'إطار بدون إنفجار'),
    ('All-season', 'كل المواسم'),
    ('Summer', 'صيفي'),
    ('Winter', 'شتوي'),
    ('Standard equipment', 'التجهيزات القياسية'),
    ('Sedan body style', 'هيكل سيدان'),
    ('Sportback body style', 'هيكل سبورتباك'),
    ('Coupe body style', 'هيكل كوبيه'),
    ('Cabrio body style', 'هيكل كابريوليه'),
    ('5-Cylinder Turbo (TFSI)', 'محرك 5 أسطوانات توربيني (تي إف إس آي)'),
    ('5-Cylinder Turbo', 'محرك 5 أسطوانات توربيني'),
    ('V8 Twin-Turbo', 'محرك 8 أسطوانات توربيني مزدوج'),
    ('V8 biturbo', 'محرك 8 أسطوانات توربيني مزدوج'),
    ('Tri-Motor Plaid', 'ثلاثي المحركات بليد'),
    ('Single-Speed Fixed Gear', 'تروس أحادية السرعة'),
    ('Dual-Clutch', 'مزدوج القابض'),
    ('Automatic', 'أوتوماتيك'),
    ('Manual', 'يدوي'),
    ('AWD', 'دفع رباعي'),
    ('RWD', 'دفع خلفي'),
    ('FWD', 'دفع أمامي'),
    ('4WD', 'دفع رباعي'),
    # Maintenance schedule titles
    ('Mantenimiento anual', 'الصيانة السنوية'),
    ('Revisión anual', 'الفحص السنوي'),
    ('Revisión anual básica', 'الفحص السنوي الأساسي'),
    ('Revisión intermedia', 'الفحص الدوري المتوسط'),
    ('Gran servicio', 'الصيانة الكبرى'),
    ('Correa de distribución', 'سير التوزيع'),
    ('Frenos y neumáticos', 'الفرامل والإطارات'),
    ('Suspensión y neumáticos', 'التعليق والإطارات'),
    ('Revisión de cadena', 'فحص السلسلة'),
    ('Revisión de cadena y transmisión', 'فحص السلسلة وناقل الحركة'),
    ('Revisión de híbrido', 'فحص النظام الهجين'),
    ('Revisión de turbos', 'فحص التوربينات'),
    ('Servicio de mantenimiento anual', 'خدمة الصيانة السنوية'),
    ('Cambio de aceite y filtros', 'تغيير الزيت والفلاتر'),
    ('Servicio mayor con cambio de frenos', 'الصيانة الكبرى مع تغيير الفرامل'),
    ('Servicio completo con cambio de líquidos', 'الصيانة الشاملة مع تغيير السوائل'),
    # Maintenance schedule descriptions
    ('Cambio de aceite y filtros, revisión de sistema quattro', 'تغيير الزيت والفلاتر، فحص نظام الدفع الرباعي كواترو'),
    ('Filtros, frenos, transmisión DSG y bujías', 'الفلاتر والفرامل وناقل الحركة دي إس جي والبواجي'),
    ('Revisión mayor del motor 5 cilindros, cambio de bujías y DSG', 'الفحص الرئيسي لمحرك 5 أسطوانات، تغيير البواجي وناقل الحركة دي إس جي'),
    ('Cambio de correa de distribución y tensor', 'تغيير سير التوزيع والشداد'),
    ('Cambio de discos/pastillas y juego de neumáticos performance', 'تغيير الأقراص/الفحمات ومجموعة الإطارات الرياضية'),
    ('Cambio de aceite y filtros, revisión del sistema mild-hybrid de 48V.', 'تغيير الزيت والفلاتر، فحص نظام الهجين الخفيف 48 فولت.'),
    ('Cambio de filtros de aire, habitáculo y líquido de frenos.', 'تغيير فلاتر الهواء والمقصورة والسائل المكبحي.'),
    ('Revisión de motor B47, sistema de refrigeración y transmisión Steptronic.', 'فحص محرك بي 47 ونظام التبريد وناقل الحركة ستيبترونيك.'),
    ('Cambio de correa de distribución, bomba de agua y tensor.', 'تغيير سير التوزيع ومضخة الماء والشداد.'),
    ('Cambio de discos/pastillas y juego de neumáticos premium.', 'تغيير الأقراص/الفحمات ومجموعة الإطارات المميزة.'),
    ('Cambio de aceite y filtros, revisión de sistema híbrido', 'تغيير الزيت والفلاتر، فحص النظام الهجين'),
    ('Filtros, frenos, batería de alto voltaje y refrigerante', 'الفلاتر والفرامل وبطارية الجهد العالي وسوائل التبريد'),
    ('Revisión mayor del V8, cambio de bujías, transmisión y diferencial', 'الفحص الرئيسي لمحرك 8 أسطوانات، تغيير البواجي، ناقل الحركة والدفرنسي'),
    ('Cambio de discos/ pastillas y juego de neumáticos performance', 'تغيير الأقراص/الفحمات ومجموعة الإطارات الرياضية'),
    ('Inspección de cadena de distribución y componentes híbridos', 'فحص سلسلة التوزيع والمكونات الهجينة'),
    ('Cambio de aceite y filtros, revisión de sistema híbrido PHEV', 'تغيير الزيت والفلاتر، فحص النظام الهجين القابل للشحن'),
    ('Filtros, frenos, refrigerante y batería de alto voltaje', 'الفلاتر والفرامل وسوائل التبريد وبطارية الجهد العالي'),
    ('Revisión del V8 biturbo, cambio de bujías, transmisión y diferencial', 'فحص محرك 8 أسطوانات توربيني مزدوج، تغيير البواجي، ناقل الحركة والدفرنسي'),
    ('Inspección del sistema PHEV, motor eléctrico trasero y batería', 'فحص النظام الهجين القابل للشحن، المحرك الكهربائي الخلفي والبطارية'),
    ('Cambio de aceite y filtros, revisión de transmisión GR6', 'تغيير الزيت والفلاتر، فحص ناقل الحركة جي آر 6'),
    ('Filtros, refrigerante, diferenciales y bujías', 'الفلاتر وسوائل التبريد والدفرنسيات والبواجي'),
    ('Revisión mayor del VR38DETT, cambio de bujías y transmisión', 'الفحص الرئيسي لمحرك ڤي آر 38 دي إي تي تي، تغيير البواجي وناقل الحركة'),
    ('Cambio de discos/pastillas carbono-cerámicos y juego de neumáticos', 'تغيير الأقراص/الفحمات الكربونية-سيراميك ومجموعة الإطارات'),
    ('Inspección de turbos, intercoolers y sistema de refrigeración', 'فحص التوربينات والمبردات المضادة ونظام التبريد'),
    ('Cambio de aceite y filtros, revisión del sistema T-Hybrid y PDK', 'تغيير الزيت والفلاتر، فحص نظام تي هجين وبي دي كي'),
    ('Filtros, frenos, líquidos y batería de alto voltaje', 'الفلاتر والفرامل والسوائل وبطارية الجهد العالي'),
    ('Revisión del boxer turbo, bujías, transmisión PDK y diferenciales', 'فحص المحرك بوكسر تيربو، البواجي، ناقل الحركة بي دي كي والدفرنسيات'),
    ('Inspección del sistema T-Hybrid, turbos eléctricos y refrigeración', 'فحص نظام تي هجين، التوربينات الكهربائية والتبريد'),
    ('Cambio de aceite y filtros, revisión de niveles y sistemas activos', 'تغيير الزيت والفلاتر، فحص المستويات والأنظمة النشطة'),
    ('Filtros de aire, habitáculo y combustible, revisión de frenos y neumáticos', 'فلاتر الهواء والمقصورة والوقود، فحص الفرامل والإطارات'),
    ('Revisión mayor del V8 biturbo, cambio de bujías, discos y pastillas de freno', 'الفحص الرئيسي لمحرك 8 أسطوانات توربيني مزدوج، تغيير البواجي، الأقراص والفحمات'),
    ('Cambio de aceite de caja de cambios, refrigerante, líquido de frenos y dirección asistida', 'تغيير زيت ناقل الحركة، مبرد، سائل الفرامل والتوجيه المعزز'),
    ('Inspección de cadena de distribución, transmisión y diferencial', 'فحص سلسلة التوزيع، ناقل الحركة والدفرنسي'),
    ('Cambio de aceite y filtros, revisión de motor B47, sistema mild-hybrid de 48V y comprobación de niveles.', 'تغيير الزيت والفلاتر، فحص محرك بي 47، نظام الهجين الخفيف 48 فولت وفحص المستويات.'),
    ('Sustitución de filtros de aire, habitáculo y líquido de frenos. Revisión de frenos delanteros.', 'استبدال فلاتر الهواء والمقصورة والسائل المكبحي. فحص الفرامل الأمامية.'),
    ('Cambio de líquido de frenos, refrigerante de batería y revisión del tren motriz eléctrico.', 'تغيير سائل الفرامل، مبرد البطارية وفحص مجموعة المحركات الكهربائية.'),
    ('Revisión de amortiguadores, bieletas y juego de neumáticos de alto rendimiento.', 'فحص المخمدات، وصلات التعليق ومجموعة الإطارات الرياضية.'),
    # Powertrain descriptions
    ('2.5L inline-5 turbo with 407 HP and quattro AWD', 'توربيني 2.5 لتر بـ 5 أسطوانات مع 407 حصان ودفع رباعي كواترو'),
    ('2.0L diesel mild-hybrid with 197 HP and xDrive AWD', 'محرك 2.0 لتر ديزل هجين خفيف بـ 197 حصان ودفع رباعي إكس درايف'),
    ('V8 Twin-Turbo PHEV with 727 HP and AWD', 'محرك 8 أسطوانات توربيني مزدوج هجين قابل للشحن بـ 727 حصان ودفع رباعي'),
    ('V8 Twin-Turbo PHEV with 831 HP and AMG 4MATIC+ AWD', 'محرك 8 أسطوانات توربيني مزدوج هجين قابل للشحن بـ 831 حصان ودفع رباعي أي إم جي فورماتيك بلس'),
    ('V6 Twin-Turbo petrol with 600 HP and ATTESA E-TS AWD', 'محرك 6 أسطوانات توربيني مزدوج بنزين بـ 600 حصان ودفع رباعي أتيسا إي-تي-إس'),
    ('Flat-6 Twin-Turbo T-Hybrid with 711 HP and AWD', 'محرك 6 أسطوانات بوكسر توربيني مزدوج تي هجين بـ 711 حصان ودفع رباعي'),
    ('V8 4.0L biturbo, tracción Quattro AWD', 'محرك 8 أسطوانات 4.0 لتر توربيني مزدوج، دفع رباعي كواترو'),
    ('Tri-Motor Plaid AWD with 1020 HP', 'ثلاثي المحركات بليد دفع رباعي بـ 1020 حصان'),
]

WORD_REPLACEMENTS = {k.lower(): v for k, v in EXACT_REPLACEMENTS}

# Order by length descending for substring safety
ORDERED_WORDS = sorted(WORD_REPLACEMENTS.keys(), key=len, reverse=True)

# Single compiled pattern for all Latin tokens (case-insensitive, Latin-only boundaries)
WORD_PATTERN = re.compile(
    r'(?i)(?<![A-Za-z0-9])(' + '|'.join(re.escape(w) for w in ORDERED_WORDS) + r')(?![A-Za-z0-9])'
)

# Keys to skip inside Arabic sections (identifiers / internal metadata)
SKIP_KEYS = {'id', 'icon', 'category', 'hex', 'image', 'carId', 'relation'}

# Keys where only the value itself is translated (not free text with surrounding words)
VALUE_ONLY_KEYS = {'verdict', 'frequency'}

VALUE_REPLACEMENTS = {
    'buy': 'شراء',
    'avoid': 'تجنب',
    'consider': 'فكر فيها',
    'common': 'شائع',
    'occasional': 'متوسط',
    'rare': 'نادر',
}


def should_translate_key(key):
    if '.' in key:
        key = key.split('.')[-1]
    if key in SKIP_KEYS:
        return False
    return True


def translate_text(text, key=None):
    if not isinstance(text, str):
        return text
    if key and not should_translate_key(key):
        return text
    # Value-only keys: exact match only
    if key and key.split('.')[-1] in VALUE_ONLY_KEYS:
        return VALUE_REPLACEMENTS.get(text, text)
    # Translate whole phrases first
    for phrase, ar in EXACT_REPLACEMENTS:
        if text.lower() == phrase.lower():
            return ar
    # Normalize tire size, wheel-width, units, and voltage first, before word replacement
    result = text
    result = re.sub(r'(?i)(\d{2,3}/\d{2,3})\s*(?:Z?R)?(\d{2,3})', r'\1 \2', result)
    result = re.sub(r'(?i)(\d+(?:\.\d+)?)J\b', r'\1', result)
    result = re.sub(r'(?i)(\d+(?:\.\d+)?)\s*L(?![A-Za-z])', r'\1 لتر', result)
    result = re.sub(r'(?i)(\d+)\s*V\b', r'\1 فولت', result)
    result = re.sub(r'(?i)(\d+(?:\.\d+)?)\s*km', r'\1 كم', result)
    # Replace Latin tokens using a single compiled alternation
    def _replace_match(m):
        return WORD_REPLACEMENTS[m.group(1).lower()]
    result = WORD_PATTERN.sub(_replace_match, result)
    # Final fix-ups for known corrupted / residual patterns
    result = re.sub(r'(?i)(\d+)d\b', r'\1 دي', result)
    result = re.sub(r'(?i)(\d+)S\b', r'\1 إس', result)
    result = re.sub(r'(?i)(\d+)x(\d+)', r'\1×\2', result)
    result = re.sub(r'(?i)TK(\d+(?:-\d+)?)\b', r'تي كي \1', result)
    result = re.sub(r'(?i)\bR(\d+)\b', r'آر \1', result)
    result = re.sub(r'(?i)\bCd\b', r'معامل السحب', result)
    result = re.sub(r'(?i)\bWLTP\b', r'الاختبار الأوروبي الموحد', result)
    result = re.sub(r'(?i)\bNCA\b', r'نيكل كوبالت ألمنيوم', result)
    result = re.sub(r'(?i)\bV3\b', r'الجيل الثالث', result)
    result = re.sub(r'(?i)\bsurprising\b', r'مدهش', result)
    result = re.sub(r'(?i)\bminimalist\b', r'بسيط', result)
    result = re.sub(r'(?i)\bm بسيطة\b', r'بسيطة', result)
    result = re.sub(r'أمáximo\b', r'الحد الأقصى', result)
    result = re.sub(r'أمبيرño\b', r'سنة', result)
    result = re.sub(r'أمبيرñأو إس\b', r'سنوات', result)
    return result


def normalize_ar_value(value):
    """If a value inside an Arabic branch is a multilingual dict, return its Arabic content."""
    if isinstance(value, dict) and set(value.keys()) <= LANG_KEYS and 'ar' in value:
        return value['ar']
    return value


def translate_obj(obj, key_path=''):
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            new_key = f'{key_path}.{k}' if key_path else k
            v = normalize_ar_value(v)
            if isinstance(v, (dict, list)):
                out[k] = translate_obj(v, new_key)
            elif isinstance(v, str):
                out[k] = translate_text(v, new_key) if should_translate_key(new_key) else v
            else:
                out[k] = v
        return out
    elif isinstance(obj, list):
        return [translate_obj(normalize_ar_value(item), key_path + f'[{i}') for i, item in enumerate(obj)]
    elif isinstance(obj, str):
        return translate_text(obj, key_path)
    return obj


def translate_car_file(path):
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Translate Arabic branches of multilingual sections
    for section in ['review', 'drivingExperience', 'exteriorDesign', 'interior', 'technology',
                    'interiorCards', 'interiorText', 'tires', 'safety', 'ownership', 'runningCosts',
                    'problems', 'ownerReviews', 'profileData', 'usedGuide', 'pageText']:
        if section not in data:
            continue
        sec = data[section]
        if not (isinstance(sec, dict) and 'ar' in sec and set(sec.keys()) <= LANG_KEYS):
            continue
        sec['ar'] = translate_obj(sec['ar'], section + '.ar')

    # pageText.ar
    if 'pageText' in data and isinstance(data['pageText'], dict) and 'ar' in data['pageText']:
        data['pageText']['ar'] = translate_obj(data['pageText']['ar'], 'pageText.ar')

    # ownerReviews may be inside ownership
    if 'ownership' in data and isinstance(data['ownership'], dict) and 'ar' in data['ownership']:
        ar = data['ownership']['ar']
        if isinstance(ar, dict) and 'ownerReviews' in ar:
            ar['ownerReviews'] = translate_obj(ar['ownerReviews'], 'ownership.ar.ownerReviews')

    FUEL_TYPE_MAP = {
        'petrol': 'بنزين',
        'gasoline': 'بنزين',
        'gasolina': 'بنزين',
        'diesel': 'ديزل',
        'electric': 'كهرباء',
        'electricity': 'كهرباء',
        'electrico': 'كهرباء',
        'hybrid': 'هجين',
        'híbrido': 'هجين',
        'phev': 'هجين قابلة للشحن',
        'mild-hybrid': 'هجين خفيف',
        'mild hybrid': 'هجين خفيف',
        'plug-in hybrid': 'هجين قابلة للشحن',
        'plug-in-hybrid': 'هجين قابلة للشحن',
        'plug in hybrid': 'هجين قابلة للشحن',
    }

    # Arabic-specific top-level fields (re-translate any Latin tokens)
    AR_FIELDS = ['nameAr', 'fullModelNameAr', 'badgeAr', 'taglineAr', 'typeAr', 'drivetrainAr']
    for field in AR_FIELDS:
        if field in data and isinstance(data[field], str):
            data[field] = translate_text(data[field], field)
    if 'specs' in data and isinstance(data['specs'], dict):
        for sub in ['engine', 'transmission', 'drivetrain']:
            if sub in data['specs'] and isinstance(data['specs'][sub], dict):
                sub_obj = data['specs'][sub]
                # generate typeAr from type if missing
                if 'type' in sub_obj and isinstance(sub_obj['type'], str):
                    if 'typeAr' not in sub_obj or not isinstance(sub_obj['typeAr'], str) or not sub_obj['typeAr'].strip():
                        sub_obj['typeAr'] = translate_text(sub_obj['type'], f'specs.{sub}.typeAr')
                for field in ['typeAr', 'nameAr']:
                    if field in sub_obj and isinstance(sub_obj[field], str):
                        sub_obj[field] = translate_text(sub_obj[field], f'specs.{sub}.{field}')
        if 'engine' in data['specs'] and isinstance(data['specs']['engine'], dict):
            engine = data['specs']['engine']
            if 'fuelType' in engine and isinstance(engine['fuelType'], str):
                ft = engine['fuelType'].lower()
                engine['fuelTypeAr'] = FUEL_TYPE_MAP.get(ft, translate_text(engine['fuelType'], 'specs.engine.fuelTypeAr'))

    # Powertrain description
    if 'powertrain' in data and isinstance(data['powertrain'], dict):
        if 'description' in data['powertrain'] and isinstance(data['powertrain']['description'], str):
            data['powertrain']['descriptionAr'] = translate_text(data['powertrain']['description'], 'powertrain.descriptionAr')

    # Content timeline (maintenance schedule) — generate Arabic fields
    def translate_timeline_item(item, key_path):
        if not isinstance(item, dict):
            return
        for key in ['title', 'desc', 'service', 'description']:
            if key in item and isinstance(item[key], str):
                ar_key = key + 'Ar'
                item[ar_key] = translate_text(item[key], f'{key_path}.{ar_key}')

    if 'content' in data and isinstance(data['content'], dict) and isinstance(data['content'].get('timeline'), list):
        for i, item in enumerate(data['content']['timeline']):
            translate_timeline_item(item, f'content.timeline[{i}]')

    # Version feature lists — generate Arabic fields
    if 'versions' in data and isinstance(data['versions'], list):
        for v in data['versions']:
            if isinstance(v, dict) and isinstance(v.get('features'), list):
                v['featuresAr'] = [translate_text(f, 'versions.featuresAr') for f in v['features']]

    # Comparisons
    if 'comparisons' in data and isinstance(data['comparisons'], list):
        for c in data['comparisons']:
            if isinstance(c, dict):
                for field in ['nameAr', 'fullNameAr']:
                    if field in c and isinstance(c[field], str):
                        c[field] = translate_text(c[field], f'comparisons.{field}')
    elif 'comparisons' in data and isinstance(data['comparisons'], dict):
        for c in data['comparisons'].values():
            if isinstance(c, dict):
                for field in ['nameAr', 'fullNameAr']:
                    if field in c and isinstance(c[field], str):
                        c[field] = translate_text(c[field], f'comparisons.{field}')

    # Option names: add or update nameAr
    if 'options' in data and isinstance(data['options'], list):
        for opt in data['options']:
            if isinstance(opt, dict) and 'name' in opt:
                opt['nameAr'] = translate_text(opt.get('nameAr') or opt['name'], 'options.nameAr')

    # Version names: add or update nameAr
    if 'versions' in data and isinstance(data['versions'], list):
        for v in data['versions']:
            if isinstance(v, dict) and 'name' in v:
                v['nameAr'] = translate_text(v.get('nameAr') or v['name'], 'versions.nameAr')
                if 'fullNameAr' in v and isinstance(v['fullNameAr'], str):
                    v['fullNameAr'] = translate_text(v['fullNameAr'], 'versions.fullNameAr')
    elif 'versions' in data and isinstance(data['versions'], dict):
        for v in data['versions'].values():
            if isinstance(v, dict) and 'name' in v:
                v['nameAr'] = translate_text(v.get('nameAr') or v['name'], 'versions.nameAr')
                if 'fullNameAr' in v and isinstance(v['fullNameAr'], str):
                    v['fullNameAr'] = translate_text(v['fullNameAr'], 'versions.fullNameAr')

    # color names: if 'name' inside ar branch is dict, flatten to ar
    if 'exteriorDesign' in data and isinstance(data['exteriorDesign'], dict) and 'ar' in data['exteriorDesign']:
        ar = data['exteriorDesign']['ar']
        if isinstance(ar, dict) and 'colors' in ar and isinstance(ar['colors'], list):
            for c in ar['colors']:
                if isinstance(c, dict) and isinstance(c.get('name'), dict) and set(c['name'].keys()) <= LANG_KEYS and 'ar' in c['name']:
                    c['name'] = c['name']['ar']
                if isinstance(c, dict) and isinstance(c.get('name'), str):
                    c['name'] = translate_text(c['name'], 'exteriorDesign.ar.colors.name')

    # Tires: flatten ar branch if nested
    if 'tires' in data and isinstance(data['tires'], dict) and 'ar' in data['tires']:
        ar = data['tires']['ar']
        if isinstance(ar, dict):
            for k, v in ar.items():
                if isinstance(v, dict) and set(v.keys()) <= LANG_KEYS and 'ar' in v:
                    ar[k] = v['ar']

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


for fname in sorted(os.listdir(DATA_DIR)):
    if not fname.endswith('.json'):
        continue
    translate_car_file(os.path.join(DATA_DIR, fname))

print('Translated Arabic content across all car files.')
